version: '3'
services:
  nginx:
    logging:
      driver: "json-file"
      options:
        tag: "nginx"

  mongo:
    logging:
      driver: "json-file"
      options:
        tag: "mongo"

  backend:
    logging:
      driver: "json-file"
      options:
        tag: "backend"
    command: ["nodemon", "index.js"]

  admin:
    logging:
      driver: "json-file"
      options:
        tag: "admin"
    command: ["nodemon", "index.js"]

  account:
    logging:
      driver: "json-file"
      options:
        tag: "account"
    command: ["nodemon", "index.js"]

  frontend:
    logging:
      driver: "json-file"
      options:
        tag: "frontend"
    command: ["nodemon", "index.js"]

networks:
  proxy:
  node:
